image: gradle:alpine

stages:
  - test

variables:
  PLATFORM:
    value: "android"
    options:
      - "android"
      - "ios"
    description: "Platform for test execution"
  TYPE:
    value: "sauce"
    options:
      - "sauce"
      - "bstack"
    description: "Driver type for test execution"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - chmod +x ./gradlew
  - source .env

test:
  stage: test
  rules:
    - when: always
  script: 
    - echo "Running MOBILE test cases with Serenity-BDD on BrowserStack"
    - ./gradlew clean test --tests "*.TestCartRunner" -Dplatform=$PLATFORM -Dtype=$TYPE
    
  artifacts:
    when: always
    name: "Serenity MOBILE Report"
    paths:
    - target/site/serenity
    expire_in: 24h
